# Generated by Django 6.0.5 on 2026-05-14 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('ordenador', 'Ordenador'), ('impresora', 'Impresora'), ('monitor', 'Monitor'), ('servidor', 'Servidor'), ('switch', 'Switch'), ('router', 'Router'), ('telefono', 'Teléfono'), ('otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('en_reparacion', 'En reparación'), ('dado_de_baja', 'Dado de baja')], default='activo', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('gestionado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de inventario',
                'verbose_name_plural': 'Items de inventario',
                'ordering': ['nombre'],
            },
        ),
    ]
