# Generated by Django 6.0.5 on 2026-05-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='activo',
            new_name='is_active',
        ),
    ]
